# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mr_ros.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mr_ros.proto',
  package='RosInterface',
  syntax='proto2',
  serialized_pb=_b('\n\x0cmr_ros.proto\x12\x0cRosInterface\",\n\x0bSpeedCourse\x12\r\n\x05speed\x18\x01 \x02(\x01\x12\x0e\n\x06\x63ourse\x18\x02 \x02(\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SPEEDCOURSE = _descriptor.Descriptor(
  name='SpeedCourse',
  full_name='RosInterface.SpeedCourse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='speed', full_name='RosInterface.SpeedCourse.speed', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='course', full_name='RosInterface.SpeedCourse.course', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=74,
)

DESCRIPTOR.message_types_by_name['SpeedCourse'] = _SPEEDCOURSE

SpeedCourse = _reflection.GeneratedProtocolMessageType('SpeedCourse', (_message.Message,), dict(
  DESCRIPTOR = _SPEEDCOURSE,
  __module__ = 'mr_ros_pb2'
  # @@protoc_insertion_point(class_scope:RosInterface.SpeedCourse)
  ))
_sym_db.RegisterMessage(SpeedCourse)


# @@protoc_insertion_point(module_scope)
