obstacle_range: 12.0
raytrace_range: 10.0
footprint: [[0.35, 0.3], [-0.35, 0.3], [-0.35, -0.3], [0.35, -0.3], [0.45, 0.0]]
robot_radius: 0.5
inflation_radius: 1.0
cost_scaling_factor: 2.58

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}
